### ISSUE TITLE
Dynamic Linking Error loading "node_modules/@teradataprebuilt/nativelib-win32/teradatasql.dll": "Win32 error 126

### ISSUE THREAD

**Issue by markddrake** [Teradata/nodejs-driver#15]
Upgraded to node 14.4. Cleared out my node_modules folder and reinstalled everything using this package.json 

```
{
  "name": "yadamu",
  "version": "1.0.0",
  "description": "User Interface for YADAMU",
  "main": "main.js",
  "scripts": {
    "start": "electron ./"
  },
  "repository": {
    "type": "git",
    "url": "TBD"
  },
  "author": "Mark D Drake",
  "license": "SEE LICENSE IN TDB.txt",
  "dependencies": {
    "@teradataprebuilt/fastcall-win32-node-v64": "^0.2.6",
    "@teradataprebuilt/nativelib-win32": "^1.0.0-beta.1",
    "bootstrap": "^4.4.1",
    "cookie-parser": "^1.4.5",
    "express": "^4.17.1",
    "express-session": "^1.17.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.5.0",
    "mariadb": "^2.3.1",
    "mongodb": "^3.5.7",
    "mssql": "^6.2.0",
    "mysql": "^2.18.1",
    "oracledb": "^4.2.0",
    "pg": "^8.0.3",
    "pg-copy-streams": "^2.2.2",
    "pg-query-stream": "^2.1.2",
    "popper.js": "^1.16.1",
    "snowflake-sdk": "^1.5.2",
    "teradata-nodejs-driver": "^1.0.0-rc.2",
    "uuid": "^8.0.0",
    "wkx": "^0.5.0"
  },
  "devDependencies": {
    "electron": "^9.0.3"
  }
}
```
When I run my app it fails with..
```
ConnectionError: Dynamic Linking Error loading "node_modules/@teradataprebuilt/nativelib-win32/teradatasql.dll": "Win32 error 126
```
I took the liberty of modifying line 74 to read 
```
  throw new Error(`Dynamic Linking Error loading "${path}": "${err}`);
```
So I could see what it was failing on.

Here's the full stack
```

C:\Development\YADAMU>
C:\Development\YADAMU>node C:\Development\YADAMU\app\YADAMU_QA\common\node\test.js CONFIG=qa\work\dbcopy2.jSON 
2020-06-10T03:20:51.368Z [QA][Environemnt][x64][win32][v14.4.0]: Running tests
2020-06-10T03:20:54.529Z [TRACE][Teradata][Primary]: getConnectionFromPool()
2020-06-10T03:20:54.559Z [ERROR][DBROUNDTRIP][TASK]: Caught exception
ConnectionError: Dynamic Linking Error loading "node_modules/@teradataprebuilt/nativelib-win32/teradatasql.dll": "Win32 error 126
    at TeradataQA.getConnectionFromPool (C:\Development\YADAMU\app\YADAMU\teradata\node\teradataDBI.js:155:15)
    at TeradataQA.getDatabaseConnectionImpl (C:\Development\YADAMU\app\YADAMU\common\yadamuDBI.js:435:36)
    at async TeradataQA.getDatabaseConnection (C:\Development\YADAMU\app\YADAMU\common\yadamuDBI.js:565:9)
    at async TeradataQA.initialize (C:\Development\YADAMU\app\YADAMU\common\yadamuDBI.js:633:7)
    at async TeradataQA.initialize (C:\Development\YADAMU\app\YADAMU\teradata\node\teradataDBI.js:229:6)
    at async TeradataQA.initialize (C:\Development\YADAMU\app\YADAMU_QA\teradata\node\teradataQA.js:11:4)
    at async YadamuTest.doPumpOperation (C:\Development\YADAMU\app\YADAMU\common\yadamu.js:509:7)
    at async YadamuTest.pumpData (C:\Development\YADAMU\app\YADAMU\common\yadamu.js:597:21)
    at async YadamuQA.dbRoundtrip (C:\Development\YADAMU\app\YADAMU_QA\common\node\yadamuQA.js:824:20)
    at async YadamuQA.doTests (C:\Development\YADAMU\app\YADAMU_QA\common\node\yadamuQA.js:1265:14) {
  cause: TeradataError: Dynamic Linking Error loading "node_modules/@teradataprebuilt/nativelib-win32/teradatasql.dll": "Win32 error 126
      at TeradataQA.getConnectionFromPool (C:\Development\YADAMU\app\YADAMU\teradata\node\teradataDBI.js:155:15)
      at TeradataQA.getDatabaseConnectionImpl (C:\Development\YADAMU\app\YADAMU\common\yadamuDBI.js:435:36)
      at async TeradataQA.getDatabaseConnection (C:\Development\YADAMU\app\YADAMU\common\yadamuDBI.js:565:9)
      at async TeradataQA.initialize (C:\Development\YADAMU\app\YADAMU\common\yadamuDBI.js:633:7)
      at async TeradataQA.initialize (C:\Development\YADAMU\app\YADAMU\teradata\node\teradataDBI.js:229:6)
      at async TeradataQA.initialize (C:\Development\YADAMU\app\YADAMU_QA\teradata\node\teradataQA.js:11:4)
      at async YadamuTest.doPumpOperation (C:\Development\YADAMU\app\YADAMU\common\yadamu.js:509:7)
      at async YadamuTest.pumpData (C:\Development\YADAMU\app\YADAMU\common\yadamu.js:597:21)
      at async YadamuQA.dbRoundtrip (C:\Development\YADAMU\app\YADAMU_QA\common\node\yadamuQA.js:824:20)
      at async YadamuQA.doTests (C:\Development\YADAMU\app\YADAMU_QA\common\node\yadamuQA.js:1265:14) {
    cause: Error: Dynamic Linking Error loading "node_modules/@teradataprebuilt/nativelib-win32/teradatasql.dll": "Win32 error 126
        at new DynamicLibrary (C:\Development\YADAMU\app\node_modules\ffi-napi\lib\dynamic_library.js:74:11)
        at Object.Library (C:\Development\YADAMU\app\node_modules\ffi-napi\lib\library.js:45:14)
        at new TeradataConnection (C:\Development\YADAMU\app\node_modules\teradata-nodejs-driver\teradata-connection.js:34:24)
        at TeradataQA.getConnectionFromPool (C:\Development\YADAMU\app\YADAMU\teradata\node\teradataDBI.js:158:33)
        at TeradataQA.getDatabaseConnectionImpl (C:\Development\YADAMU\app\YADAMU\common\yadamuDBI.js:435:36)
        at async TeradataQA.getDatabaseConnection (C:\Development\YADAMU\app\YADAMU\common\yadamuDBI.js:565:9)
        at async TeradataQA.initialize (C:\Development\YADAMU\app\YADAMU\common\yadamuDBI.js:633:7)
        at async TeradataQA.initialize (C:\Development\YADAMU\app\YADAMU\teradata\node\teradataDBI.js:229:6)
        at async TeradataQA.initialize (C:\Development\YADAMU\app\YADAMU_QA\teradata\node\teradataQA.js:11:4)
        at async YadamuTest.doPumpOperation (C:\Development\YADAMU\app\YADAMU\common\yadamu.js:509:7),
    sql: 'Oracledb.Pool.getConnection()'
  },
  connectionProperties: {
    host: '192.168.1.195',
    user: 'dbc',
    password: '************',
    log: '0'
  }
}
2020-06-10T03:20:54.564Z [ERROR][DBROUNDTRIP][FAILED]: Elapsed Time: 00:00:03.196s
2020-06-10T03:20:54.564Z [QA][TEST][qa\work\dbcopy2.jSON]: Elapsed Time: 00:00:03.196s.
```
As you can see I appear to have the required dll in the location in question

```
C:\Development\YADAMU>dir node_modules\@teradataprebuilt\nativelib-win32
 Volume in drive C has no label.
 Volume Serial Number is 862F-A063

 Directory of C:\Development\YADAMU\node_modules\@teradataprebuilt\nativelib-win32

06/10/2020  03:19 AM    <DIR>          .
06/10/2020  03:19 AM    <DIR>          ..
06/10/2020  03:12 AM             2,249 package.json
04/10/2019  06:41 AM               127 README.md
04/10/2019  06:57 AM        10,530,495 teradatasql.dll
04/10/2019  06:57 AM             4,270 teradatasql.h
               4 File(s)     10,537,141 bytes
               2 Dir(s)  173,952,475,136 bytes free

C:\Development\YADAMU>
```
It still appears to me that the driver is making an assumption that the 'node_modules' folder is a direct descendant of the folder where the node application is being run from. While I have made sure that this is a valid assumption for this testcase, I do not think that it is a safe general assumption. In my case it would "app/node_modules/teradataprebuilt" had I not copied the "@teradataprebuilt "folder to the location where the driver is looking for it.

**Comment by markddrake** [comment]
Jeremy I found a work around. After adding the folder containing the node_modules folder (In my case "c:\development\yadamu\app") to my PATH  environment variable the driver could correctly locate the required DLL.

**Comment by jeremysmartt** [comment]
That’s good news.  Also with rc2, you no longer need to have this dependency:
@teradataprebuilt/fastcall-win32-node-v64

**Comment by markddrake** [comment]
I still think I shouldn't have to add something to my path to get the driver to load. I think it should be able to locate the folder containing the DLL itself using the same logic that node uses to search for the node_modules folder, and then resolve the path to the driver before attempting to load it.

**Comment by markddrake** [comment]
Anyway I am able to make progress now, so thanks for the effort in getting the updated driver out so quickly. I'm now back into trying to learn Teradata SQL so I can get the SQL bits of YADAMU running on Teredata. Once I have those ported I should be able to get a first cut of a working Teradata interface up and running. I must admit I am concerned about performance, at least theoretically, given the lack of streaming reads and bulk inserts. but we'll see what happens once I have interface up and running.

**Comment by jeremysmartt** [comment]
Agree about the pathing and shouldn’t have to do the work around.  I see you are using electron, so might be something with the difference there and regular node as haven’t seen the need to change the path env variable in regular node.  Will take a look and see about electron though and glad you can make progress by setting the Path env variable for electron for now.

**Comment by markddrake** [comment]
Don't want you going off a a wild goose chase, I don't think it's electron related (yet). YADAMU is primary run as a service or as a command line tool. The electron component simply provides a very simple user interface for people who find the command lines scary :). At the moment I am prototyping the Teradata interface via the command line, so it's a plain simple node command line environment at this point.

**Comment by rexsuecia** [comment]
I have the same problem when deploying using AWS Lambda. The node_modules is _not_ located in the root but rather in `/opt/nodejs/node_modules`. In this case it is the linux so lib that is not found (`node_modules/@teradataprebuilt/nativelib-linux/teradatasql.so`) 

Would be quite easy to add a configuration parameter in the constructor?

https://github.com/Teradata/nodejs-driver/blob/4ed0efed1e9b77ada7006e33aefdc8a226af4c54/src/teradata-connection.ts#L43

Would you accept a PR?

**Comment by jeremysmartt** [comment]
@rexsuecia Yes, please add a PR for review, thanks!

**Comment by adamtwo** [comment]
All,

we have just released teradata-nodejs-driver 1.0.0-rc.5. This version uses `require.resolve()` call to locate `@teradataprebuilt/nativelib` dependencies. Since this is node.js API it should be able to locate your `node_modules` directory the same way node.js resolves your other dependencies. We have done extensive testing on Linux, MacOS and Windows 10. I've not tried it in Lambda but can't think of a reason why it would fail there.

Could you please upgrade to 1.0.0-rc.5 and let us know if you encounter any issues?

**Comment by rexsuecia** [comment]
I have successfully run the new rc.5 in both AWS Lambda (Nodejs 12.x) and on windows (nodejs 14, x86_64) no issues as far as I can tell. Thanks for the support this far!

**Comment by adamtwo** [comment]
Thanks @rexsuecia for testing it out. Great to hear it's working with AWS Lambda. I'm closing the issue.
