### ISSUE TITLE
Errors in macOS Catalina

### ISSUE THREAD

**Issue by RobeeeJay** [Teradata/nodejs-driver#16]
Hi! 👋

I am currently struggling to run this under macOS Catalina, with either Node 8 (beta 2) or Node 12 (RC 2).

Node 8 gives me this error:
```
TypeError: Cannot load library or library not found: node_modules/@teradataprebuilt/nativelib-darwin/teradatasql.dylib
    at Library.initialize (/Users/robee/teradata/node_modules/@teradataprebuilt/fastcall-darwin-node-v57/lib/Library.js:82:37)
    at Library._addFunction (/Users/robee/teradata/node_modules/@teradataprebuilt/fastcall-darwin-node-v57/lib/Library.js:170:14)
    at Library.syncFunction (/Users/robee/teradata/node_modules/@teradataprebuilt/fastcall-darwin-node-v57/lib/Library.js:134:14)
    at Library.function (/Users/robee/teradata/node_modules/@teradataprebuilt/fastcall-darwin-node-v57/lib/Library.js:129:18)
    at new TeradataConnection (/Users/robee/teradata/node_modules/teradata-nodejs-driver/teradata-connection.js:57:26)
    at Object.<anonymous> (/Users/robee/teradata/index.js:12:26)
    at Module._compile (module.js:650:14)
    at Object.Module._extensions..js (module.js:664:10)
```

Node 12 gives me this error:
```
Error: Dynamic Linking Error: dlopen(node_modules/@teradataprebuilt/nativelib-darwin/teradatasql.dylib, 2): image not found
    at new DynamicLibrary (/Users/robee/teradata/node_modules/ffi-napi/lib/dynamic_library.js:74:11)
    at Object.Library (/Users/robee/teradata/node_modules/ffi-napi/lib/library.js:45:14)
    at new TeradataConnection (/Users/robee/teradata/node_modules/teradata-nodejs-driver/teradata-connection.js:34:24)
    at Object.<anonymous> (/Users/robee/teradata/index.js:12:26)
    at Module._compile (internal/modules/cjs/loader.js:1135:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Has anybody come across this before, do you know? :(

**Comment by RobeeeJay** [comment]
Answering my own question, it appears this is very sensitive to the current working directory, if that isn't set properly it is unable to find the image file even though it exists.
