### ISSUE TITLE
Execute Many Insert fails with The transaction exceeded the maximum number of rowhash locks allowed with 40,000 rows

### ISSUE THREAD

**Issue by markddrake** [Teradata/nodejs-driver#21]
With the following table..

```

CREATE SET TABLE X1.CUSTOMERS ,FALLBACK ,      NO BEFORE JOURNAL,      NO AFTER JOURNAL,      CHECKSUM = DEFAULT,      DEFAULT MERGEBLOCKRATIO,      MAP = TD_MAP1      (       CUST_ID DECIMAL(38,0),       CUST_FIRST_NAME VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_LAST_NAME VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_GENDER CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_YEAR_OF_BIRTH DECIMAL(4,0),       CUST_MARITAL_STATUS VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_STREET_ADDRESS VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_POSTAL_CODE VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_CITY VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_CITY_ID DECIMAL(38,0),       CUST_STATE_PROVINCE VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_STATE_PROVINCE_ID DECIMAL(38,0),       COUNTRY_ID DECIMAL(38,0),       CUST_MAIN_PHONE_NUMBER VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_INCOME_LEVEL VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_CREDIT_LIMIT DECIMAL(38,0),       CUST_EMAIL VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_TOTAL VARCHAR(14) CHARACTER SET LATIN NOT CASESPECIFIC,       CUST_TOTAL_ID DECIMAL(38,0),       CUST_SRC_ID DECIMAL(38,0),       CUST_EFF_FROM DATE FORMAT 'YY/MM/DD',       CUST_EFF_TO DATE FORMAT 'YY/MM/DD',       CUST_VALID VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC) PRIMARY INDEX ( CUST_ID );
--
```
The following insert fails
```
insert into "X1"."CUSTOMERS" ("CUST_ID","CUST_FIRST_NAME","CUST_LAST_NAME","CUST_GENDER","CUST_YEAR_OF_BIRTH","CUST_MARITAL_STATUS","CUST_STREET_ADDRESS","CUST_POSTAL_CODE","CUST_CITY","CUST_CITY_ID","CUST_STATE_PROVINCE","CUST_STATE_PROVINCE_ID","COUNTRY_ID","CUST_MAIN_PHONE_NUMBER","CUST_INCOME_LEVEL","CUST_CREDIT_LIMIT","CUST_EMAIL",
"CUST_TOTAL","CUST_TOTAL_ID","CUST_SRC_ID","CUST_EFF_FROM","CUST_EFF_TO","CUST_VALID") values ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
```
with 
```
OperationalError: [Version 42659830765e8ee7b720b821cd0b35677b82dbd5] [Session 1213] [Teradata Database] [Error 9128] The transaction exceeded the maximum number of rowhash locks allowed.
  at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1072
  at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1088
  at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1127
  at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1170
  at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:296
  at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122
  at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:1751
  at database/sql.ctxDriverQuery ctxutil.go:48
  at database/sql.(*DB).queryDC.func1 sql.go:1464
  at database/sql.withLock sql.go:3032
  at database/sql.(*DB).queryDC sql.go:1459
  at database/sql.(*Conn).QueryContext sql.go:1701
  at main.goCreateRows goside.go:545
  at main.jsgoCreateRows goside.go:441
  at main._cgoexpwrap_5ee1dc57f81d_jsgoCreateRows _cgo_gotypes.go:292
  at runtime.call64 asm_amd64.s:574
  at runtime.cgocallbackg1 cgocall.go:316
  at runtime.cgocallbackg cgocall.go:194
  at runtime.cgocallback_gofunc asm_amd64.s:826
  at runtime.goexit asm_amd64.s:2361
     at TeradataCursor.executemany (C:\Development\YADAMU\app\node_modules\teradata-nodejs-driver\teradata-cursor.js:168:23)
     at TeradataCursor.execute (C:\Development\YADAMU\app\node_modules\teradata-nodejs-driver\teradata-cursor.js:91:22)
     at TeradataQA.executeSQL (C:\Development\YADAMU\app\YADAMU\teradata\node\teradataDBI.js:208:16)
```
It fails on the 4th block of 10,000 rows. My logic commits after 50,000 For what it's worth on narrower tables I have successfully insert 900,000 records using the same 10,000/50,000 logic

**Comment by markddrake** [comment]
If I switch to a 10,000/20,000 strategy then the insert process completes normally. I failed to undestand why the 10,000/50,000 strategy works with a narrow table but fails with a wider table. Surely it should not be function of the number of columns ...
