### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by SatishChGit** [Teradata/nodejs-driver#7]
Atom Version: 1.40. x64, windows, 
Electron: 3.1.10
Chrome: 66.0.3359.181
Node: v10.2.0
---------------------------------
When I try to use nodejs-driver in atom package, throwing error as 
Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)

**Comment by SatishChGit** [comment]
Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///C:/Users/sc250072/AppData/Local/atom/app-1.40.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\sc250072\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:146745)
    at bindings (C:\Users\sc250072\github\td-connector\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\sc250072\github\td-connector\node_modules\@teradataprebuilt\fastcall-win32-node-v64\lib\ref-libs\ref.js:5:47)
    at Object.<anonymous> (C:\Users\sc250072\github\td-connector\node_modules\@teradataprebuilt\fastcall-win32-node-v64\lib\ref-libs\ref.js:1458:3)
    at Module.get_Module._compile (C:\Users\sc250072\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\sc250072\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///C:/Users/sc250072/AppData/Local/atom/app-1.40.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\sc250072\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (C:\Users\sc250072\github\td-connector\node_modules\@teradataprebuilt\fastcall-win32-node-v64\lib\index.js:21:19)
    at Object.<anonymous> (C:\Users\sc250072\github\td-connector\node_modules\@teradataprebuilt\fastcall-win32-node-v64\lib\index.js:33:3)
    at Module.get_Module._compile (C:\Users\sc250072\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\sc250072\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///C:/Users/sc250072/AppData/Local/atom/app-1.40.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\sc250072\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (C:\Users\sc250072\github\td-connector\node_modules\teradata-nodejs-driver\teradata-connection.js:11:16)
    at Object.<anonymous> (C:\Users\sc250072\github\td-connector\node_modules\teradata-nodejs-driver\teradata-connection.js:133:3)
    at Module.get_Module._compile (C:\Users\sc250072\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11:147429)
